/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kuis2;

/**
 *
 * @author ASUS
 */
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;

public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nikTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        jkLakiRadio = new javax.swing.JRadioButton();
        jkPerempuanRadio = new javax.swing.JRadioButton();
        basketCheckBox = new javax.swing.JCheckBox();
        futsalCheckBox = new javax.swing.JCheckBox();
        badmintonCheckBox = new javax.swing.JCheckBox();
        voliCheckBox = new javax.swing.JCheckBox();
        teleponTextField = new javax.swing.JTextField();
        tanggalFormatField = new javax.swing.JFormattedTextField();
        pendidikanComboBox = new javax.swing.JComboBox<>();
        ipkFormatField = new javax.swing.JFormattedTextField();
        daftarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIK");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Hobi");

        jLabel6.setText("Telepon");

        jLabel7.setText("Tanggal Lahir");

        jLabel8.setText("Pendidikan");

        jLabel9.setText("IPK");

        nikTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikTextFieldActionPerformed(evt);
            }
        });

        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        jScrollPane1.setViewportView(alamatTextArea);

        buttonGroup1.add(jkLakiRadio);
        jkLakiRadio.setText("Laki-laki");
        jkLakiRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkLakiRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jkPerempuanRadio);
        jkPerempuanRadio.setText("Perempuan");

        basketCheckBox.setText("Basket");

        futsalCheckBox.setText("Futsal");

        badmintonCheckBox.setText("Badminton");

        voliCheckBox.setText("Voli");

        teleponTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teleponTextFieldActionPerformed(evt);
            }
        });
        teleponTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teleponTextFieldKeyPressed(evt);
            }
        });

        tanggalFormatField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tanggalFormatFieldFocusLost(evt);
            }
        });
        tanggalFormatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalFormatFieldActionPerformed(evt);
            }
        });
        tanggalFormatField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tanggalFormatFieldKeyReleased(evt);
            }
        });

        pendidikanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "D1", "D2", "D3", "D4/S1", "S2", "S3" }));
        pendidikanComboBox.setSelectedIndex(-1);

        ipkFormatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipkFormatFieldActionPerformed(evt);
            }
        });
        ipkFormatField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ipkFormatFieldKeyReleased(evt);
            }
        });

        daftarButton.setText("Daftar");
        daftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nikTextField)
                            .addComponent(namaTextField)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jkLakiRadio)
                                    .addComponent(basketCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(badmintonCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(futsalCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jkPerempuanRadio)
                                    .addComponent(voliCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(daftarButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tanggalFormatField)
                                .addComponent(pendidikanComboBox, 0, 212, Short.MAX_VALUE)
                                .addComponent(ipkFormatField)))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jkLakiRadio)
                            .addComponent(jkPerempuanRadio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(basketCheckBox)
                            .addComponent(futsalCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(badmintonCheckBox)
                            .addComponent(voliCheckBox))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(teleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tanggalFormatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pendidikanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(ipkFormatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(daftarButton)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jkLakiRadio.setActionCommand("Laki-laki");
        jkPerempuanRadio.setActionCommand("Perempuan");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jkLakiRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkLakiRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkLakiRadioActionPerformed

    private void teleponTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teleponTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_teleponTextFieldActionPerformed

    private void nikTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikTextFieldActionPerformed

    private void tanggalFormatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalFormatFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tanggalFormatFieldActionPerformed

    private void ipkFormatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipkFormatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipkFormatFieldActionPerformed

    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarButtonActionPerformed
        // TODO add your handling code here:
        String nik = nikTextField.getText();
        String nama = namaTextField.getText();
        String alamat = alamatTextArea.getText();
        String pendidikan = pendidikanComboBox.getSelectedItem().toString(); // UPPERCASE agar memudahkan pengecekan
        String ipkText = ipkFormatField.getText();
        String tanggalLahir = tanggalFormatField.getText();
        try {
            double ipk = Double.parseDouble(ipkText); // Konversi input IPK ke double

            // Cek apakah memenuhi syarat pendidikan dan IPK
            if (!pendidikan.equals("D1") && !pendidikan.equals("D2")
                    && !pendidikan.equals("D3") && !pendidikan.equals("D4/S1") && !pendidikan.equals("S2") && !pendidikan.equals("S3")) {
                JOptionPane.showMessageDialog(this, "Tidak memenuhi pendidikan minimal D1",
                        "Pendaftaran Gagal", JOptionPane.ERROR_MESSAGE);
            } else if (ipk < 3.01) {
                JOptionPane.showMessageDialog(this, "Tidak memenuhi IPK minimal 3,01",
                        "Pendaftaran Gagal", JOptionPane.ERROR_MESSAGE);
            } else if (nama.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama tidak Boleh Kosong",
                        "Pendaftaran Gagal", JOptionPane.ERROR_MESSAGE);
            } else if (nik.isEmpty()) {
                JOptionPane.showMessageDialog(this, "NIK tidak Boleh Kosong",
                        "Pendaftaran Gagal", JOptionPane.ERROR_MESSAGE);
            } else if (alamat.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Alamat tidak Boleh Kosong",
                        "Pendaftaran Gagal", JOptionPane.ERROR_MESSAGE);
            } else {
                // Jika memenuhi syarat, tampilkan pesan sukses
                JOptionPane.showMessageDialog(this, "Pendaftaran berhasil!",
                        "Sukses", JOptionPane.INFORMATION_MESSAGE);
                kosongkanForm();
            }
        } catch (NumberFormatException e) {
            // Jika IPK bukan angka, tampilkan pesan kesalahan
            JOptionPane.showMessageDialog(this, "Masukkan IPK yang valid.",
                    "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_daftarButtonActionPerformed

    private void teleponTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teleponTextFieldKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            teleponTextField.setText("");
        }
    }//GEN-LAST:event_teleponTextFieldKeyPressed

    private void tanggalFormatFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tanggalFormatFieldKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tanggalFormatFieldKeyReleased

    private void tanggalFormatFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tanggalFormatFieldFocusLost
        // TODO add your handling code here:
        String input = tanggalFormatField.getText();
        try {
            Date tanggalLahir = new SimpleDateFormat("dd-MM-yyyy").parse(input);
            int umur = hitungUmur(tanggalLahir);
            if (umur < 18) {
                JOptionPane.showMessageDialog(this, "Anda belum cukup umur untuk mendaftar pekerjaan ini", "Error", JOptionPane.ERROR_MESSAGE);
                tanggalFormatField.setText("");
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Format tanggal tidak valid. Gunakan dd-MM-yyyy.", "Error", JOptionPane.ERROR_MESSAGE);
            tanggalFormatField.setText("");
        }
    }//GEN-LAST:event_tanggalFormatFieldFocusLost

    private void ipkFormatFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipkFormatFieldKeyReleased
        // TODO add your handling code here:
        try {
            double ipk = Double.parseDouble(ipkFormatField.getText());
            if (ipk < 0.0 || ipk > 4.0) {
                JOptionPane.showMessageDialog(this, "IPK tidak valid. Masukkan nilai antara 0.0 hingga 4.0", "Error", JOptionPane.ERROR_MESSAGE);
                ipkFormatField.setText("");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "IPK tidak valid. Masukkan nilai numerik yang sesuai antara 0.0 hingga 4.0", "Error", JOptionPane.ERROR_MESSAGE);
            ipkFormatField.setText("");
        }
    }//GEN-LAST:event_ipkFormatFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });

    }

    private int hitungUmur(Date tanggalLahir) {
        Date tanggalSekarang = new Date();
        long selisih = tanggalSekarang.getTime() - tanggalLahir.getTime();
        return (int) (selisih / (1000L * 60 * 60 * 24 * 365));
    }

    private void kosongkanForm() {
        nikTextField.setText("");
        namaTextField.setText("");
        alamatTextArea.setText("");
        buttonGroup1.clearSelection();
        basketCheckBox.setSelected(false);
        badmintonCheckBox.setSelected(false);
        futsalCheckBox.setSelected(false);
        voliCheckBox.setSelected(false);
        teleponTextField.setText("");
        tanggalFormatField.setText("");
        pendidikanComboBox.setSelectedIndex(-1);
        ipkFormatField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JCheckBox badmintonCheckBox;
    private javax.swing.JCheckBox basketCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton daftarButton;
    private javax.swing.JCheckBox futsalCheckBox;
    private javax.swing.JFormattedTextField ipkFormatField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jkLakiRadio;
    private javax.swing.JRadioButton jkPerempuanRadio;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nikTextField;
    private javax.swing.JComboBox<String> pendidikanComboBox;
    private javax.swing.JFormattedTextField tanggalFormatField;
    private javax.swing.JTextField teleponTextField;
    private javax.swing.JCheckBox voliCheckBox;
    // End of variables declaration//GEN-END:variables
}
